training_data = [

    ("who are you", "identity"),
    ("what is your name", "identity"),
    ("tell your name", "identity"),
    ("hu r u", "identity"),
    ("tell me about yourself", "identity"),
    ("what's your name", "identity"),
    ("I am asking your name", "identity"),
    ("tell me your name", "identity"),
    ("do you have any name", "identity"),
    ("Who are you?", "identity"),
    ("Introduce yourself.", "identity"),
    ("What's your identity?", "identity"),
    ("what about you.", "identity"),
    ("Can you introduce yourself?", "identity"),
    ("Identity of the assistant?", "identity"),
    ("What can you tell me about yourself?", "identity"),
    ("Who's behind your creation?", "identity"),
    ("Your background?", "identity"),
    ("Explain your purpose.", "identity"),
    ("tell me something yourself.", "identity"),
    ("Your role?", "identity"),
    ("I want to know more about you.", "identity"),
    ("Can you give me some information about yourself?", "identity"),
    ("Who is talking?", "identity"),
    ("Tell me your good name.", "identity"),
    ("Tell me something about yourself", "identity"),
    ("Are you a human or a machine?", "identity"),
    ("tell me if you have any name ?", "identity"),


    ("open calculator", "open app"),
    ("play solitaire", "open app"),
    ("open notepad", "open app"),
    ("Open Microsoft Word.", "open_app"),
    ("Launch Photoshop.", "open_app"),
    ("Start Spotify.", "open_app"),
    ("Open Google Chrome.", "open_app"),
    ("Run Excel.", "open_app"),
    ("Launch Visual Studio Code.", "open_app"),
    ("Start Adobe Illustrator.", "open_app"),
    ("Open VLC Media Player.", "open_app"),
    ("Launch Slack.", "open_app"),
    ("Start Zoom.", "open_app"),


    ("open YouTube", "open website"),
    ("open wikipedia", "open website"),
    ("please open youtube", "open website"),
    ("please open wikipedia", "open website"),
    ("open YouTube", "open website"),
    ("go to Facebook", "open website"),
    ("visit Wikipedia", "open website"),
    ("browse CNN", "open website"),
    ("can you open youtube", "open website"),
    ("can you open google", "open website"),
    # ("can you open yahoo", "open website"),
    # ("can you open reddit", "open website"),
    # ("can you open linkdin", "open website"),
    ("can you open twitter", "open website"),
    ("could you open youtube", "open website"),
    ("could you open google for me", "open website"),
    # ("can you open geekforgeeks", "open website"),
    # ("navigate to Reddit", "open website"),
    ("go to Twitter", "open website"),    
    ("open GitHub", "open website"),
    ("visit Stack Overflow", "open website"),
    ("go to Amazon", "open website"),
    ("explore National Geographic's website", "open website"),
    ("open Spotify", "open website"),
    ("go to LinkedIn", "open website"),
    ("visit The New York Times", "open website"),
    ("explore TED Talks", "open website"),
    ("go to BBC News site", "open website"),
    ("open Netflix", "open website"),
    ("visit Instagram", "open website"),
    ("go to eBay", "open website"),
    ("explore NASA's website", "open website"),
    ("go to Pinterest", "open website"),
    
    ("open Instagram", "open website"),
    ("visit Pinterest", "open website"),
    ("go to GitHub", "open website"),
    ("explore National Geographic's website", "open website"),
    ("open Spotify", "open website"),
    ("navigate to LinkedIn", "open website"),
    ("visit The New York Times", "open website"),
    ("explore TED Talks", "open website"),
    ("go to BBC News site", "open website"),
    ("open Netflix", "open website"),
    ("visit eBay", "open website"),
    ("explore NASA's website", "open website"),
    ("go to Wikipedia", "open website"),
    ("open Google Maps", "open website"),
    ("visit Microsoft", "open website"),
    ("explore Adobe", "open website"),
    ("go to Facebook", "open website"),
    ("visit CNN", "open website"),
    ("open Reddit", "open website"),
    ("go to Twitter", "open website"),
    ("open LinkedIn", "open website"),
    ("visit The New York Times", "open website"),
    ("explore GeekforGeeks", "open website"),


    ("play some jazz music", "play music"),
    ("play something on youtube", "play music"),
    ("play song on youtube", "play music"),
    ("start a rock playlist", "play music"),
    ("play classical music", "play music"),
    ("shuffle my favorite songs", "play music"),
    ("start the 'Chill Vibes' playlist", "play music"),
    ("play a random song", "play music"),
    ("put on some background music", "play music"),
    ("begin the 'Workout Mix'", "play music"),
    ("play top hits from the 80s", "play music"),
    ("shuffle my music library", "play music"),
    ("start the 'Mellow Beats' playlist", "play music"),
    ("play the latest pop songs", "play music"),
    ("put on some energetic music", "play music"),
    ("begin the 'Study Session' playlist", "play music"),
    ("play calming instrumental music", "play music"),
    ("shuffle my liked songs", "play music"),
    ("start a party playlist", "play music"),
    ("play upbeat tracks", "play music"),
    ("begin the 'Road Trip' playlist", "play music"),
    ("put on some indie music", "play music"),
    ("play songs for relaxation", "play music"),
    ("shuffle my recently added songs", "play music"),
    ("start the 'Feel Good' playlist", "play music"),
    ("play music for focus", "play music"),
    ("begin the 'Sunday Morning' playlist", "play music"),


    ("predict Apple stock price", "stocks"),
    ("what's the forecast for Google stock", "stocks"),
    ("analyze Tesla stock performance", "stocks"),
    ("check Microsoft stock value", "stocks"),
    ("predict Amazon stock trends", "stocks"),
    ("look up Facebook stock news", "stocks"),
    ("analyze Netflix stock performance", "stocks"),
    ("check Twitter stock value", "stocks"),
    ("predict Alibaba stock trends", "stocks"),
    ("look up IBM stock news", "stocks"),
    ("analyze Intel stock performance", "stocks"),
    ("check Coca-Cola stock value", "stocks"),
    ("predict NVIDIA stock trends", "stocks"),
    ("look up Pfizer stock news", "stocks"),
    ("analyze Zoom Video stock performance", "stocks"),
    ("check Spotify stock value", "stocks"),
    ("predict Snapchat stock trends", "stocks"),
    ("look up Johnson & Johnson stock news", "stocks"),
    ("analyze Disney stock performance", "stocks"),
    ("check Spotify stock value", "stocks"),
    ("predict AMD stock trends", "stocks"),
    ("look up Procter & Gamble stock news", "stocks"),
    ("analyze Zoom Video stock performance", "stocks"),
    ("check Spotify stock value", "stocks"),


    ("search for Python tutorials on YouTube", "youtube search"),    
    ("open the channel 'TechCrunch' on YouTube", "youtube search"),
    ("look up funny cat videos", "youtube search"),
    ("find DIY home improvement videos", "youtube search"),
    ("search for science documentaries", "youtube search"),
    ("explore makeup tutorials on YouTube", "youtube search"),
    ("look for travel vlogs", "youtube search"),
    ("find workout routines on YouTube", "youtube search"),
    ("search for cooking recipes", "youtube search"),
    ("look up music production tutorials", "youtube search"),
    ("find educational videos for kids", "youtube search"),
    ("search for gaming walkthroughs", "youtube search"),
    ("look up movie trailers", "youtube search"),
    ("find fashion haul videos", "youtube search"),
    ("search for technology reviews on YouTube", "youtube search"),
    ("look up sports highlights", "youtube search"),
    ("find dance tutorials", "youtube search"),
    ("search for TED Talks", "youtube search"),
    ("look up travel destination videos", "youtube search"),
    ("find car maintenance tutorials on YouTube", "youtube search"),
    ("search for language learning videos", "youtube search"),
    ("look up pet training tips", "youtube search"),
    ("find book review videos", "youtube search"),
    ("search for art and drawing tutorials", "youtube search"),
    # Add more examples if needed


    ("download an image of a cat", "scrap images"),
    ("save a picture of a sunset", "scrap images"),
    ("download an image of a mountain landscape", "scrap images"),
    ("save a picture of a beach", "scrap images"),
    ("download an image of a cute puppy", "scrap images"),
    ("save a picture of a city skyline", "scrap images"),
    ("download an image of a tropical island", "scrap images"),
    ("save a picture of a colorful flower", "scrap images"),
    ("download an image of a space nebula", "scrap images"),
    ("save a picture of a vintage car", "scrap images"),
    ("download an image of a snowy landscape", "scrap images"),
    ("save a picture of a famous landmark", "scrap images"),
    ("download an image of a delicious dessert", "scrap images"),
    ("save a picture of a wildlife safari", "scrap images"),
    ("download an image of a historic monument", "scrap images"),
    ("save a picture of a technology gadget", "scrap images"),
    ("download an image of a sports event", "scrap images"),
    ("save a picture of a cultural festival", "scrap images"),
    ("download an image of a vintage book cover", "scrap images"),
    ("save a picture of a modern architecture", "scrap images"),
    ("download an image of a rare bird", "scrap images"),
    ("save a picture of a beautiful sunrise", "scrap images"),
    ("download an image of a retro fashion", "scrap images"),
    ("save a picture of an artistic painting", "scrap images"),
    # Add more examples if needed


    # Add more examples for each class
    # Balance the dataset with a variety of examples
    # ...
    ("search for Elon Musk images", "google search"),
    ("show pictures of the Eiffel Tower", "google search"),
    ("search for Python programming language", "google search"),
    ("look up information about the Eiffel Tower", "google search"),
    ("find the capital of Japan", "google search"),
    ("search for healthy dinner recipes", "google search"),
    ("look up the latest technology news", "google search"),
    ("find the definition of 'serendipity'", "google search"),
    ("search for DIY home decor ideas", "google search"),
    ("look up the benefits of meditation", "google search"),
    ("find interesting facts about dolphins", "google search"),
    ("search for travel destinations in Europe", "google search"),
    ("look up reviews for the movie 'Inception'", "google search"),
    ("find information about space exploration", "google search"),
    ("search for home gardening tips", "google search"),
    ("look up historical events from the 19th century", "google search"),
    ("find the lyrics to the song 'Imagine' by John Lennon", "google search"),
    ("search for tips on productivity", "google search"),
    ("look up information about renewable energy", "google search"),
    ("find the best hiking trails near me", "google search"),
    ("search for virtual art exhibitions", "google search"),
    ("look up famous quotes by Albert Einstein", "google search"),
    ("find the best budget-friendly recipes", "google search"),
    ("search for coding tutorials for beginners", "google search"),
    ("look up information about climate change", "google search"),
    ("find the latest fashion trends", "google search"),

    ("Tell me a joke", "joke"),
    ("Share a funny story", "joke"),
    ("Make me laugh", "joke"),
    ("Why did the chicken cross the road?", "joke"),
    ("Knock, knock", "joke"),
    ("Tell me a humorous anecdote", "joke"),
    ("What's the funniest thing you've heard?", "joke"),
    ("Give me a good laugh", "joke"),
    ("Share a joke about technology", "joke"),
    ("Make my day with a joke", "joke"),
    ("Tell a light-hearted joke", "joke"),
    ("I need a good laugh", "joke"),
    ("Can you make me smile?", "joke"),
    ("Humor me with a joke", "joke"),
    ("What's your favorite joke?", "joke"),
    ("Say something funny", "joke"),
    ("Make me giggle", "joke"),
    ("Tell a quick joke", "joke"),
    ("Bring on the humor", "joke"),
    # Add more examples if needed

    ("Tell me a story", "story"),
    ("Share an interesting tale", "story"),
    ("Narrate a short story", "story"),
    ("What's a good bedtime story?", "story"),
    ("Create a fictional narrative", "story"),
    ("Transport me with a story", "story"),
    ("Share a mystery story", "story"),
    ("Tell a story with a twist", "story"),
    ("I want to hear a fairy tale", "story"),
    ("Spin a yarn for me", "story"),
    ("Narrate an adventure story", "story"),
    ("What's your favorite story?", "story"),
    ("I'm in the mood for a story", "story"),
    ("Tell a story about space", "story"),
    ("Share a spooky story", "story"),
    ("Give me a thrilling story", "story"),
    ("I need a good story", "story"),
    ("Entertain me with a story", "story"),
    ("Create a fantasy story", "story"),
    # Add more examples if needed
    
    
    ("Tell me an interesting fact", "fact"),
    ("Share a fun trivia", "fact"),
    ("Give me a random fact", "fact"),
    ("Teach me something new", "fact"),
    ("What's a surprising fact?", "fact"),
    ("Impress me with a fact", "fact"),
    ("Educate me with a fact", "fact"),
    ("Share a historical fact", "fact"),
    ("Tell me a science fact", "fact"),
    ("What's a cool fact about animals?", "fact"),
    ("Enlighten me with a fact", "fact"),
    ("Give me a mind-blowing fact", "fact"),
    ("Tell me a bizarre fact", "fact"),
    ("What's a fact about space?", "fact"),
    ("Share an unbelievable fact", "fact"),
    ("Tell me a fun historical tidbit", "fact"),
    ("Educate me with a surprising fact", "fact"),
    ("Impress me with your knowledge", "fact"),
    ("Give me a quick fact", "fact"),
    ("tell me some fact", "fact"),
    # Add more examples if needed


    # ("How are you?", "chat"),
    ("What's up?", "chat"),
    ("Tell me about your day", "chat"),
    ("How do you feel?", "chat"),
    ("What's on your mind?", "chat"),
    ("Do you have feelings?", "chat"),
    ("Chat with me", "chat"),
    ("Let's have a conversation", "chat"),
    ("Can we talk?", "chat"),
    ("What's your favorite color?", "chat"),
    ("How's the weather?", "chat"),
    ("Share your thoughts", "chat"),
    ("Talk to me", "chat"),
    ("What do you like?", "chat"),
    ("Tell me a secret", "chat"),
    ("Write me an email", "chat"),
    ("Chatbot, entertain me", "chat"),
    ("Just saying hello", "chat"),
    ("Ask me a question", "chat"),
    ("what is the colour of shark skin?", "chat"),
    ("what should be perfect time for gym", "chat"),
    ("do you know something about plants", "chat"),
    ("what would elon doing this time", "chat"),
    ("tell me some random things", "chat"),
    ("need your help", "chat"),
    ("suggest me some projects on programming", "chat"),
    ("tell me some random things", "chat"),
    ("How are you doing today?", "chat"),
    ("What's your favorite color?", "chat"),
    ("What's the weather like today?", "chat"),
    ("How was your day?", "chat"),
    ("What do you like to do in your free time?", "chat"),
    ("Do you have any siblings?", "chat"),
    ("Can you recommend a good book?", "chat"),
    ("What's your opinion on artificial intelligence?", "chat"),
    ("What's the latest news?", "chat"),
    ("Who is your favorite musician?", "chat"),
    ("What's your favorite movie?", "chat"),
    ("Do you like pizza?", "chat"),
    ("What's the meaning of life?", "chat"),
    ("What's the best way to relax?", "chat"),
    ("What's your favorite hobby?", "chat"),
    ("Can you sing a song?", "chat"),
    ("What's your dream destination?", "chat"),
    ("Do you believe in aliens?", "chat"),
    ("What's the best advice you've ever received?", "chat"),
    ("Tell me something interesting.", "chat"),
    ("What's the most challenging thing you've faced?", "chat"),
    ("Do you like sports?", "chat"),
    ("Tell me a riddle.", "chat"),
    ("What's the most beautiful place you've visited?", "chat"),
    ("What's the key to happiness?", "chat"),
    ("What's your favorite quote?", "chat"),
    ("What's your favorite animal?", "chat"),
    ("Tell me about a challenge you've overcome.", "chat"),
    ("Do you like to travel?", "chat"),
    ("What's your favorite place in the world?", "chat"),
    ("Tell me something about yourself.", "chat"),


    ("What's the date today?", "date_time"),
    ("Tell me the current time", "date_time"),
    ("What day is it?", "date_time"),
    ("What's the time now?", "date_time"),
    ("Tell me the date", "date_time"),
    ("Can you inform me about the day?", "date_time"),
    ("Give me the current date and time", "date_time"),
    ("What's today's date?", "date_time"),
    ("Inform me about the time", "date_time"),
    ("Tell me the day of the week", "date_time"),
    ("Give me the current time and date", "date_time"),
    ("What's the time at the moment?", "date_time"),
    ("Inform me about today's date", "date_time"),
    ("What time is it now?", "date_time"),
    ("Tell me the current date", "date_time"),
    ("What's the day today?", "date_time"),
    ("provide the current time?", "date_time"),
    ("Let me know the date", "date_time"),
    ("What's the current day?", "date_time"),
    ("Can you tell me the time?", "date_time"),
    ("Give me the date today", "date_time"),
    ("What's the current date and time?", "date_time"),
    ("Tell me today's date and time", "date_time"),

    
    ("What's my internet speed?", "speed_check"),
    ("Can you check my internet speed?", "speed_check"),
    ("How fast is my internet?", "speed_check"),
    ("Check the speed of my internet connection.", "speed_check"),
    ("Is my internet fast enough?", "speed_check"),
    ("What is the current speed of my internet?", "speed_check"),
    ("Test my internet speed.", "speed_check"),
    ("How good is my internet connection?", "speed_check"),
    ("Check if my internet is slow.", "speed_check"),
    ("Is my internet speed satisfactory?", "speed_check"),


    ("Goodbye.", "exit"),
    ("Exit the application.", "exit"),
    ("Quit the model.", "exit"),
    ("Close Jarvis.", "exit"),
    ("Say goodbye.", "exit"),
    ("Shutdown the assistant.", "exit"),
    ("End the conversation.", "exit"),
    ("Close the program.", "exit"),
    ("Terminate the model.", "exit"),
    ("See you later.", "exit"),
    ("Shut down, Jarvis.", "exit"),
    ("Finish the session.", "exit"),
    ("Say farewell.", "exit"),
    ("Turn off the assistant.", "exit"),
    ("End our talk.", "exit"),   
]


if __name__ == '__main__':
    pass

